<?php

namespace Database\Seeders\General\Nav;

use App\Models\Application;
use App\Models\Method;
use Illuminate\Database\Seeder;

class MethodSeeder extends Seeder
{
    public function run(): void
    {
        Method::insert([
        // 'countries' application methods
            // 'countries' application 'view' method
            [
                'name' => 'countries view',
                'code' => Application::where('short', 'country')->first()->code . '-V',
                'short' => 'view',
                'disc' => 'view all countries',
                'application_id' => Application::where('short', 'country')->first()->id,
                'sub_module_id' => Application::where('short', 'country')->subModule->id,
                'module_id' => Application::where('short', 'country')->module->id,
                'view' => Application::where('short', 'country')->first()->view . '.view',
                'component' => Application::where('short', 'country')->first()->component . 'View',
                'permissions' => null,
                'log' => json_encode(['created' => ['time' => now(), 'created_by' => 'system']]),
                'settings' => json_encode(['display-columns' => null, 'show-columns' => null, 'selected-columns' => null, 'main_view' => null]),
            ],
            // 'countries' application 'show' method
            [
                'name' => 'countries show',
                'code' => Application::where('short', 'country')->first()->code . '-S',
                'short' => 'show',
                'disc' => 'show details of a country',
                'application_id' => Application::where('short', 'country')->first()->id,
                'sub_module_id' => Application::where('short', 'country')->subModule->id,
                'module_id' => Application::where('short', 'country')->module->id,
                'view' => Application::where('short', 'country')->first()->view . '.show',
                'component' => Application::where('short', 'country')->first()->component . 'Show',
                'permissions' => null,
                'log' => json_encode(['created' => ['time' => now(), 'created_by' => 'system']]),
                'settings' => json_encode(['display-columns' => null, 'show-columns' => null, 'selected-columns' => null, 'main_view' => null]),
            ],
            // 'countries' application 'form' method
            [
                'name' => 'countries form',
                'code' => Application::where('short', 'country')->first()->code . '-F',
                'short' => 'form',
                'disc' => 'form for creating or editing countries',
                'application_id' => Application::where('short', 'country')->first()->id,
                'sub_module_id' => Application::where('short', 'country')->subModule->id,
                'module_id' => Application::where('short', 'country')->module->id,
                'view' => Application::where('short', 'country')->first()->view . '.form',
                'component' => Application::where('short', 'country')->first()->component . 'Form',
                'permissions' => null,
                'log' => json_encode(['created' => ['time' => now(), 'created_by' => 'system']]),
                'settings' => json_encode(['display-columns' => null, 'show-columns' => null, 'selected-columns' => null, 'main_view' => null]),
            ],
            // 'countries' application 'create' method
            [
                'name' => 'countries create',
                'code' => Application::where('short', 'country')->first()->code . '-C',
                'short' => 'create',
                'disc' => 'create a new country',
                'application_id' => Application::where('short', 'country')->first()->id,
                'sub_module_id' => Application::where('short', 'country')->subModule->id,
                'module_id' => Application::where('short', 'country')->module->id,
                'view' => Application::where('short', 'country')->first()->view . '.create',
                'component' => Application::where('short', 'country')->first()->component . 'Create',
                'permissions' => null,
                'log' => json_encode(['created' => ['time' => now(), 'created_by' => 'system']]),
                'settings' => json_encode(['display-columns' => null, 'show-columns' => null, 'selected-columns' => null, 'main_view' => null]),
            ],
            // 'countries' application 'delete' method
            [
                'name' => 'countries delete',
                'code' => Application::where('short', 'country')->first()->code . '-D',
                'short' => 'delete',
                'disc' => 'delete a country',
                'application_id' => Application::where('short', 'country')->first()->id,
                'sub_module_id' => Application::where('short', 'country')->subModule->id,
                'module_id' => Application::where('short', 'country')->module->id,
                'view' => Application::where('short', 'country')->first()->view . '.delete',
                'component' => Application::where('short', 'country')->first()->component . 'Delete',
                'permissions' => null,
                'log' => json_encode(['created' => ['time' => now(), 'created_by' => 'system']]),
                'settings' => json_encode(['display-columns' => null, 'show-columns' => null, 'selected-columns' => null, 'main_view' => null]),
            ],
            // 'countries' application 'update' method
            [
                'name' => 'countries update',
                'code' => Application::where('short', 'country')->first()->code . '-U',
                'short' => 'update',
                'disc' => 'update country details',
                'application_id' => Application::where('short', 'country')->first()->id,
                'sub_module_id' => Application::where('short', 'country')->subModule->id,
                'module_id' => Application::where('short', 'country')->module->id,
                'view' => Application::where('short', 'country')->first()->view . '.update',
                'component' => Application::where('short', 'country')->first()->component . 'Update',
                'permissions' => null,
                'log' => json_encode(['created' => ['time' => now(), 'created_by' => 'system']]),
                'settings' => json_encode(['display-columns' => null, 'show-columns' => null, 'selected-columns' => null, 'main_view' => null]),
            ],
        // 'states' application methods
            // 'states' application 'view' method
            [
                'name' => 'states view',
                'code' => Application::where('short', 'state')->first()->code . '-V',
                'short' => 'view',
                'disc' => 'view all states',
                'application_id' => Application::where('short', 'state')->first()->id,
                'sub_module_id' => Application::where('short', 'state')->subModule->id,
                'module_id' => Application::where('short', 'state')->module->id,
                'view' => Application::where('short', 'state')->first()->view . '.view',
                'component' => Application::where('short', 'state')->first()->component . 'View',
                'permissions' => null,
                'log' => json_encode(['created' => ['time' => now(), 'created_by' => 'system']]),
                'settings' => json_encode(['display-columns' => null, 'show-columns' => null, 'selected-columns' => null, 'main_view' => null]),
            ],
            // 'states' application 'show' method
            [
                'name' => 'states show',
                'code' => Application::where('short', 'state')->first()->code . '-S',
                'short' => 'show',
                'disc' => 'show details of a state',
                'application_id' => Application::where('short', 'state')->first()->id,
                'sub_module_id' => Application::where('short', 'state')->subModule->id,
                'module_id' => Application::where('short', 'state')->module->id,
                'view' => Application::where('short', 'state')->first()->view . '.show',
                'component' => Application::where('short', 'state')->first()->component . 'Show',
                'permissions' => null,
                'log' => json_encode(['created' => ['time' => now(), 'created_by' => 'system']]),
                'settings' => json_encode(['display-columns' => null, 'show-columns' => null, 'selected-columns' => null, 'main_view' => null]),
            ],
            // 'states' application 'form' method
            [
                'name' => 'states form',
                'code' => Application::where('short', 'state')->first()->code . '-F',
                'short' => 'form',
                'disc' => 'form for creating or editing states',
                'application_id' => Application::where('short', 'state')->first()->id,
                'sub_module_id' => Application::where('short', 'state')->subModule->id,
                'module_id' => Application::where('short', 'state')->module->id,
                'view' => Application::where('short', 'state')->first()->view . '.form',
                'component' => Application::where('short', 'state')->first()->component . 'Form',
                'permissions' => null,
                'log' => json_encode(['created' => ['time' => now(), 'created_by' => 'system']]),
                'settings' => json_encode(['display-columns' => null, 'show-columns' => null, 'selected-columns' => null, 'main_view' => null]),
            ],
            // 'states' application 'create' method
            [
                'name' => 'states create',
                'code' => Application::where('short', 'state')->first()->code . '-C',
                'short' => 'create',
                'disc' => 'create a new state',
                'application_id' => Application::where('short', 'state')->first()->id,
                'sub_module_id' => Application::where('short', 'state')->subModule->id,
                'module_id' => Application::where('short', 'state')->module->id,
                'view' => Application::where('short', 'state')->first()->view . '.create',
                'component' => Application::where('short', 'state')->first()->component . 'Create',
                'permissions' => null,
                'log' => json_encode(['created' => ['time' => now(), 'created_by' => 'system']]),
                'settings' => json_encode(['display-columns' => null, 'show-columns' => null, 'selected-columns' => null, 'main_view' => null]),
            ],
            // 'states' application 'delete' method
            [
                'name' => 'states delete',
                'code' => Application::where('short', 'state')->first()->code . '-D',
                'short' => 'delete',
                'disc' => 'delete a state',
                'application_id' => Application::where('short', 'state')->first()->id,
                'sub_module_id' => Application::where('short', 'state')->subModule->id,
                'module_id' => Application::where('short', 'state')->module->id,
                'view' => Application::where('short', 'state')->first()->view . '.delete',
                'component' => Application::where('short', 'state')->first()->component . 'Delete',
                'permissions' => null,
                'log' => json_encode(['created' => ['time' => now(), 'created_by' => 'system']]),
                'settings' => json_encode(['display-columns' => null, 'show-columns' => null, 'selected-columns' => null, 'main_view' => null]),
            ],
            // 'states' application 'update' method
            [
                'name' => 'states update',
                'code' => Application::where('short', 'state')->first()->code . '-U',
                'short' => 'update',
                'disc' => 'update state details',
                'application_id' => Application::where('short', 'state')->first()->id,
                'sub_module_id' => Application::where('short', 'state')->subModule->id,
                'module_id' => Application::where('short', 'state')->module->id,
                'view' => Application::where('short', 'state')->first()->view . '.update',
                'component' => Application::where('short', 'state')->first()->component . 'Update',
                'permissions' => null,
                'log' => json_encode(['created' => ['time' => now(), 'created_by' => 'system']]),
                'settings' => json_encode(['display-columns' => null, 'show-columns' => null, 'selected-columns' => null, 'main_view' => null]),
            ],
        // 'states' application methods
            // 'cities' application 'view' method
            [
                'name' => 'cities view',
                'code' => Application::where('short', 'city')->first()->code . '-V',
                'short' => 'view',
                'disc' => 'view all cities',
                'application_id' => Application::where('short', 'city')->first()->id,
                'sub_module_id' => Application::where('short', 'city')->subModule->id,
                'module_id' => Application::where('short', 'city')->module->id,
                'view' => Application::where('short', 'city')->first()->view . '.view',
                'component' => Application::where('short', 'city')->first()->component . 'View',
                'permissions' => null,
                'log' => json_encode(['created' => ['time' => now(), 'created_by' => 'system']]),
                'settings' => json_encode(['display-columns' => null, 'show-columns' => null, 'selected-columns' => null, 'main_view' => null]),
            ],
            // 'cities' application 'show' method
            [
                'name' => 'cities show',
                'code' => Application::where('short', 'city')->first()->code . '-S',
                'short' => 'show',
                'disc' => 'show details of a city',
                'application_id' => Application::where('short', 'city')->first()->id,
                'sub_module_id' => Application::where('short', 'city')->subModule->id,
                'module_id' => Application::where('short', 'city')->module->id,
                'view' => Application::where('short', 'city')->first()->view . '.show',
                'component' => Application::where('short', 'city')->first()->component . 'Show',
                'permissions' => null,
                'log' => json_encode(['created' => ['time' => now(), 'created_by' => 'system']]),
                'settings' => json_encode(['display-columns' => null, 'show-columns' => null, 'selected-columns' => null, 'main_view' => null]),
            ],
            // 'cities' application 'form' method
            [
                'name' => 'cities form',
                'code' => Application::where('short', 'city')->first()->code . '-F',
                'short' => 'form',
                'disc' => 'form for creating or editing cities',
                'application_id' => Application::where('short', 'city')->first()->id,
                'sub_module_id' => Application::where('short', 'city')->subModule->id,
                'module_id' => Application::where('short', 'city')->module->id,
                'view' => Application::where('short', 'city')->first()->view . '.form',
                'component' => Application::where('short', 'city')->first()->component . 'Form',
                'permissions' => null,
                'log' => json_encode(['created' => ['time' => now(), 'created_by' => 'system']]),
                'settings' => json_encode(['display-columns' => null, 'show-columns' => null, 'selected-columns' => null, 'main_view' => null]),
            ],
            // 'cities' application 'create' method
            [
                'name' => 'cities create',
                'code' => Application::where('short', 'city')->first()->code . '-C',
                'short' => 'create',
                'disc' => 'create a new city',
                'application_id' => Application::where('short', 'city')->first()->id,
                'sub_module_id' => Application::where('short', 'city')->subModule->id,
                'module_id' => Application::where('short', 'city')->module->id,
                'view' => Application::where('short', 'city')->first()->view . '.create',
                'component' => Application::where('short', 'city')->first()->component . 'Create',
                'permissions' => null,
                'log' => json_encode(['created' => ['time' => now(), 'created_by' => 'system']]),
                'settings' => json_encode(['display-columns' => null, 'show-columns' => null, 'selected-columns' => null, 'main_view' => null]),
            ],
            // 'cities' application 'delete' method
            [
                'name' => 'cities delete',
                'code' => Application::where('short', 'city')->first()->code . '-D',
                'short' => 'delete',
                'disc' => 'delete a city',
                'application_id' => Application::where('short', 'city')->first()->id,
                'sub_module_id' => Application::where('short', 'city')->subModule->id,
                'module_id' => Application::where('short', 'city')->module->id,
                'view' => Application::where('short', 'city')->first()->view . '.delete',
                'component' => Application::where('short', 'city')->first()->component . 'Delete',
                'permissions' => null,
                'log' => json_encode(['created' => ['time' => now(), 'created_by' => 'system']]),
                'settings' => json_encode(['display-columns' => null, 'show-columns' => null, 'selected-columns' => null, 'main_view' => null]),
            ],
            // 'cities' application 'update' method
            [
                'name' => 'cities update',
                'code' => Application::where('short', 'city')->first()->code . '-U',
                'short' => 'update',
                'disc' => 'update city details',
                'application_id' => Application::where('short', 'city')->first()->id,
                'sub_module_id' => Application::where('short', 'city')->subModule->id,
                'module_id' => Application::where('short', 'city')->module->id,
                'view' => Application::where('short', 'city')->first()->view . '.update',
                'component' => Application::where('short', 'city')->first()->component . 'Update',
                'permissions' => null,
                'log' => json_encode(['created' => ['time' => now(), 'created_by' => 'system']]),
                'settings' => json_encode(['display-columns' => null, 'show-columns' => null, 'selected-columns' => null, 'main_view' => null]),
            ],

        ]);
    }
}
